# fly.toml app configuration file generated for tokyo-metro-interactive-map on 2024-04-29T00:25:36+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tokyo-metro-interactive-map'
primary_region = 'sea'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
